services:
  postgres:
    image: postgres:15-alpine
    container_name: bifrost-postgres
    environment:
      POSTGRES_DB: bifrost
      POSTGRES_USER: bifrost
      POSTGRES_PASSWORD: bifrost123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bifrost -d bifrost"]
      interval: 5s
      timeout: 5s
      retries: 5

  dex:
    image: dexidp/dex:v2.37.0
    container_name: bifrost-dex
    ports:
      - "5556:5556"
      - "5558:5558"
    volumes:
      - ./dex-config.yaml:/etc/dex/config.yaml:ro
    command: ["dex", "serve", "/etc/dex/config.yaml"]
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: